### ISSUE TITLE
Perp88 - staking underlying balances 

### ISSUE THREAD

**Issue by witem** [defiyield-app/defiyield-self-integrations#17]
## Bug Report

**Current Behavior**
Missed balances for underlying tokens cause problems with internal calculation for underlying balances(based on reserve and pool share. Which causes a problem with UI result, example(`0x841f4b2c13223fce62cace03f4c9b4ecadcff1ee`):
![image](https://user-images.githubusercontent.com/1782530/215472483-68ce7cbb-37bc-492e-b635-b60e339b7887.png)

**Expected behavior**

Fetch and add user balances for each underlying token so that it will be similar to the original UI:
![image](https://user-images.githubusercontent.com/1782530/215472806-db32590e-81bc-4d13-98e6-0c8b7fac90cb.png)

**Details**

- Chain: polygon
- Project Website: Perp88

**Additional context/Screenshots**

Initial PR: https://github.com/defiyield-app/defiyield-self-integrations/pull/3

@chentang88158, please take a look if you want to improve how it is displayed.

**Comment by chentang88158** [comment]
To make it clear,  I have to fix `FetchUserPosition` of PoolSupplied by overrides reserve of each token to user balance?  or add response for supplied of each underlying token?  like this [plpPoolSupplied, btcPoolSupplied,maticPoolSupplied, ...]

**Comment by witem** [comment]
@chentang88158, you need to add the correct balance for each token here: https://github.com/defiyield-app/defiyield-self-integrations/blob/33bc72caaea3508e8daaa6dc23f044387c5c815c/apps/workshop/projects/Perp88/modules/PLPStaking.ts#L158

**Comment by chentang88158** [comment]
> @chentang88158, you need to add the correct balance for each token here:
> 
> https://github.com/defiyield-app/defiyield-self-integrations/blob/33bc72caaea3508e8daaa6dc23f044387c5c815c/apps/workshop/projects/Perp88/modules/PLPStaking.ts#L158

Thank for response, another question about balance of underlying.

e.g. user bought 100 PLP with USDC and staked in our pool, (assume plp =1 usdc), and user holding 888 usdc in his wallet
plp balance = 100
display of balance usdc should be 100 or 888 in this case?  
and what happened if I set zero?

**Comment by chentang88158** [comment]
> set balance to zero?

Thank you, I only want to display PLP balance, no need to token breakdown anymore. I will create pull request for this.

**Comment by chentang88158** [comment]
@witem 
please checked on this pr[https://github.com/defiyield-app/defiyield-self-integrations/pull/23](url)

**Comment by witem** [comment]
@chentang88158 thanks for the PR. The result on the screenshot is what do you expect?
![image](https://user-images.githubusercontent.com/1782530/216581401-daa74db3-474b-430d-9017-f32c973a0d29.png)

**Comment by chentang88158** [comment]
@witem  During my review of the production environment, I observed that the claim button is disabled. What steps should I take to enable the claim functionality?

**Comment by witem** [comment]
Hi @chentang88158 ,
For now, it's not exposed to self-integrated protocols. We have this in plans, and we will announce it after release.
