### ISSUE TITLE
PLP APR and TVL is incorrect 

### ISSUE THREAD

**Issue by chentang88158** [defiyield-app/defiyield-self-integrations#33]
## Bug Report

**Current Behavior**

![image](https://user-images.githubusercontent.com/115621364/218647904-33d9f930-8c69-476e-a0ad-df921179c105.png)

![image](https://user-images.githubusercontent.com/115621364/218647383-0285c896-5a05-4704-ba0f-3829c29f9062.png)

**Expected behavior**
APR  and TVL should be correct on website 
![image](https://user-images.githubusercontent.com/115621364/218647795-3db8606e-7f88-44f5-9cb8-d2155988f130.png)

TVL
![Screenshot 2023-02-14 at 12 30 12 PM](https://user-images.githubusercontent.com/115621364/218647819-23a1cdc5-f719-47ab-888b-167a3eff743a.png)

**Details**
Project Perp88
The data appeared accurate until February 13, 2023; however, it has now become inaccurate. Would you kindly investigate the issue to identify the root cause?

**Comment by witem** [comment]
@chentang88158, thanks for reporting this. This should be correct now: 
![image](https://user-images.githubusercontent.com/1782530/219044877-6b2f1317-83a0-43fe-a622-ae4bd8761310.png)

**Comment by witem** [comment]
@chentang88158 
The was with one of the RPC providers returned the wrong `totalSupply` for the PLP token

**Comment by chentang88158** [comment]
It appears that the data you have provided is still inaccurate as of February 14, 2023. I have observed a discrepancy in the Total Value Locked (TVL) at block 39279238 as compared to the values displayed on your user interface. Could it be possible that the data has not yet been fully resynchronized?

**Comment by witem** [comment]
> @witem 
> It appears that the data you have provided is still inaccurate as of February 14, 2023. I have observed a discrepancy in the Total Value Locked (TVL) at block 39279238 as compared to the values displayed on your user interface. Could it be possible that the data has not yet been fully resynchronized?

Yes, it will be resynchronized till the end of the day

**Comment by chentang88158** [comment]
@witem 
Very well, may I confirm that all data must be accurate by tomorrow?

**Comment by witem** [comment]
> @witem Very well, may I confirm that all data must be accurate by tomorrow?

`Current TVL: $1.64M`
